// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: bridge.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PBSpeedTestMode int32

const (
	PBSpeedTestMode_DOWNLOAD PBSpeedTestMode = 0
	PBSpeedTestMode_UPLOAD   PBSpeedTestMode = 1
)

// Enum value maps for PBSpeedTestMode.
var (
	PBSpeedTestMode_name = map[int32]string{
		0: "DOWNLOAD",
		1: "UPLOAD",
	}
	PBSpeedTestMode_value = map[string]int32{
		"DOWNLOAD": 0,
		"UPLOAD":   1,
	}
)

func (x PBSpeedTestMode) Enum() *PBSpeedTestMode {
	p := new(PBSpeedTestMode)
	*p = x
	return p
}

func (x PBSpeedTestMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PBSpeedTestMode) Descriptor() protoreflect.EnumDescriptor {
	return file_bridge_proto_enumTypes[0].Descriptor()
}

func (PBSpeedTestMode) Type() protoreflect.EnumType {
	return &file_bridge_proto_enumTypes[0]
}

func (x PBSpeedTestMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PBSpeedTestMode.Descriptor instead.
func (PBSpeedTestMode) EnumDescriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{0}
}

type PBWorkerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBWorkerInfo) Reset() {
	*x = PBWorkerInfo{}
	mi := &file_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBWorkerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBWorkerInfo) ProtoMessage() {}

func (x *PBWorkerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBWorkerInfo.ProtoReflect.Descriptor instead.
func (*PBWorkerInfo) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *PBWorkerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PBWorkerInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PBWorkerInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type PBWorkerInfoList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workers       []*PBWorkerInfo        `protobuf:"bytes,1,rep,name=workers,proto3" json:"workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBWorkerInfoList) Reset() {
	*x = PBWorkerInfoList{}
	mi := &file_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBWorkerInfoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBWorkerInfoList) ProtoMessage() {}

func (x *PBWorkerInfoList) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBWorkerInfoList.ProtoReflect.Descriptor instead.
func (*PBWorkerInfoList) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *PBWorkerInfoList) GetWorkers() []*PBWorkerInfo {
	if x != nil {
		return x.Workers
	}
	return nil
}

type PBProxyConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	ConnUri       string                 `protobuf:"bytes,2,opt,name=conn_uri,json=connUri,proto3" json:"conn_uri,omitempty"`
	Delay         int64                  `protobuf:"varint,3,opt,name=delay,proto3" json:"delay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBProxyConfig) Reset() {
	*x = PBProxyConfig{}
	mi := &file_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBProxyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBProxyConfig) ProtoMessage() {}

func (x *PBProxyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBProxyConfig.ProtoReflect.Descriptor instead.
func (*PBProxyConfig) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *PBProxyConfig) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *PBProxyConfig) GetConnUri() string {
	if x != nil {
		return x.ConnUri
	}
	return ""
}

func (x *PBProxyConfig) GetDelay() int64 {
	if x != nil {
		return x.Delay
	}
	return 0
}

type PBProxyConfigList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*PBProxyConfig       `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBProxyConfigList) Reset() {
	*x = PBProxyConfigList{}
	mi := &file_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBProxyConfigList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBProxyConfigList) ProtoMessage() {}

func (x *PBProxyConfigList) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBProxyConfigList.ProtoReflect.Descriptor instead.
func (*PBProxyConfigList) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *PBProxyConfigList) GetConfigs() []*PBProxyConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

type PBStringMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         map[string]string      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBStringMap) Reset() {
	*x = PBStringMap{}
	mi := &file_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBStringMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBStringMap) ProtoMessage() {}

func (x *PBStringMap) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBStringMap.ProtoReflect.Descriptor instead.
func (*PBStringMap) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{4}
}

func (x *PBStringMap) GetItems() map[string]string {
	if x != nil {
		return x.Items
	}
	return nil
}

type PBDiscoverWorkersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LibraryPath   string                 `protobuf:"bytes,1,opt,name=library_path,json=libraryPath,proto3" json:"library_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBDiscoverWorkersRequest) Reset() {
	*x = PBDiscoverWorkersRequest{}
	mi := &file_bridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBDiscoverWorkersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBDiscoverWorkersRequest) ProtoMessage() {}

func (x *PBDiscoverWorkersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBDiscoverWorkersRequest.ProtoReflect.Descriptor instead.
func (*PBDiscoverWorkersRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{5}
}

func (x *PBDiscoverWorkersRequest) GetLibraryPath() string {
	if x != nil {
		return x.LibraryPath
	}
	return ""
}

type PBDiscoverWorkersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workers       *PBWorkerInfoList      `protobuf:"bytes,1,opt,name=workers,proto3" json:"workers,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBDiscoverWorkersResponse) Reset() {
	*x = PBDiscoverWorkersResponse{}
	mi := &file_bridge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBDiscoverWorkersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBDiscoverWorkersResponse) ProtoMessage() {}

func (x *PBDiscoverWorkersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBDiscoverWorkersResponse.ProtoReflect.Descriptor instead.
func (*PBDiscoverWorkersResponse) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{6}
}

func (x *PBDiscoverWorkersResponse) GetWorkers() *PBWorkerInfoList {
	if x != nil {
		return x.Workers
	}
	return nil
}

func (x *PBDiscoverWorkersResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type PBInitializeRunnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerPath    string                 `protobuf:"bytes,1,opt,name=worker_path,json=workerPath,proto3" json:"worker_path,omitempty"`
	LowMemMode    bool                   `protobuf:"varint,2,opt,name=low_mem_mode,json=lowMemMode,proto3" json:"low_mem_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBInitializeRunnerRequest) Reset() {
	*x = PBInitializeRunnerRequest{}
	mi := &file_bridge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBInitializeRunnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBInitializeRunnerRequest) ProtoMessage() {}

func (x *PBInitializeRunnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBInitializeRunnerRequest.ProtoReflect.Descriptor instead.
func (*PBInitializeRunnerRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{7}
}

func (x *PBInitializeRunnerRequest) GetWorkerPath() string {
	if x != nil {
		return x.WorkerPath
	}
	return ""
}

func (x *PBInitializeRunnerRequest) GetLowMemMode() bool {
	if x != nil {
		return x.LowMemMode
	}
	return false
}

type PBInitializeRunnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBInitializeRunnerResponse) Reset() {
	*x = PBInitializeRunnerResponse{}
	mi := &file_bridge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBInitializeRunnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBInitializeRunnerResponse) ProtoMessage() {}

func (x *PBInitializeRunnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBInitializeRunnerResponse.ProtoReflect.Descriptor instead.
func (*PBInitializeRunnerResponse) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{8}
}

func (x *PBInitializeRunnerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PBInitializeRunnerResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type PBParseConfigsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParseErrors   *PBStringMap           `protobuf:"bytes,1,opt,name=parse_errors,json=parseErrors,proto3" json:"parse_errors,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBParseConfigsResponse) Reset() {
	*x = PBParseConfigsResponse{}
	mi := &file_bridge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBParseConfigsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBParseConfigsResponse) ProtoMessage() {}

func (x *PBParseConfigsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBParseConfigsResponse.ProtoReflect.Descriptor instead.
func (*PBParseConfigsResponse) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{9}
}

func (x *PBParseConfigsResponse) GetParseErrors() *PBStringMap {
	if x != nil {
		return x.ParseErrors
	}
	return nil
}

func (x *PBParseConfigsResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type PBValidateConfigsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ValidateErrors *PBStringMap           `protobuf:"bytes,1,opt,name=validate_errors,json=validateErrors,proto3" json:"validate_errors,omitempty"`
	Error          *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PBValidateConfigsResponse) Reset() {
	*x = PBValidateConfigsResponse{}
	mi := &file_bridge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBValidateConfigsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBValidateConfigsResponse) ProtoMessage() {}

func (x *PBValidateConfigsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBValidateConfigsResponse.ProtoReflect.Descriptor instead.
func (*PBValidateConfigsResponse) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{10}
}

func (x *PBValidateConfigsResponse) GetValidateErrors() *PBStringMap {
	if x != nil {
		return x.ValidateErrors
	}
	return nil
}

func (x *PBValidateConfigsResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type PBRunLatencyTestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestUrl       string                 `protobuf:"bytes,1,opt,name=test_url,json=testUrl,proto3" json:"test_url,omitempty"`
	LatencyRounds int32                  `protobuf:"varint,2,opt,name=latency_rounds,json=latencyRounds,proto3" json:"latency_rounds,omitempty"`
	RoundTimeout  int32                  `protobuf:"varint,3,opt,name=round_timeout,json=roundTimeout,proto3" json:"round_timeout,omitempty"`
	TestByBatches bool                   `protobuf:"varint,4,opt,name=test_by_batches,json=testByBatches,proto3" json:"test_by_batches,omitempty"`
	BatchSize     int32                  `protobuf:"varint,5,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBRunLatencyTestsRequest) Reset() {
	*x = PBRunLatencyTestsRequest{}
	mi := &file_bridge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBRunLatencyTestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBRunLatencyTestsRequest) ProtoMessage() {}

func (x *PBRunLatencyTestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBRunLatencyTestsRequest.ProtoReflect.Descriptor instead.
func (*PBRunLatencyTestsRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{11}
}

func (x *PBRunLatencyTestsRequest) GetTestUrl() string {
	if x != nil {
		return x.TestUrl
	}
	return ""
}

func (x *PBRunLatencyTestsRequest) GetLatencyRounds() int32 {
	if x != nil {
		return x.LatencyRounds
	}
	return 0
}

func (x *PBRunLatencyTestsRequest) GetRoundTimeout() int32 {
	if x != nil {
		return x.RoundTimeout
	}
	return 0
}

func (x *PBRunLatencyTestsRequest) GetTestByBatches() bool {
	if x != nil {
		return x.TestByBatches
	}
	return false
}

func (x *PBRunLatencyTestsRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type PBRunLatencyTestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       *PBProxyConfigList     `protobuf:"bytes,1,opt,name=configs,proto3" json:"configs,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBRunLatencyTestsResponse) Reset() {
	*x = PBRunLatencyTestsResponse{}
	mi := &file_bridge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBRunLatencyTestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBRunLatencyTestsResponse) ProtoMessage() {}

func (x *PBRunLatencyTestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBRunLatencyTestsResponse.ProtoReflect.Descriptor instead.
func (*PBRunLatencyTestsResponse) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{12}
}

func (x *PBRunLatencyTestsResponse) GetConfigs() *PBProxyConfigList {
	if x != nil {
		return x.Configs
	}
	return nil
}

func (x *PBRunLatencyTestsResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type PBDiscoverSpeedTestPresetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Presets       *PBStringMap           `protobuf:"bytes,1,opt,name=presets,proto3" json:"presets,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBDiscoverSpeedTestPresetsResponse) Reset() {
	*x = PBDiscoverSpeedTestPresetsResponse{}
	mi := &file_bridge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBDiscoverSpeedTestPresetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBDiscoverSpeedTestPresetsResponse) ProtoMessage() {}

func (x *PBDiscoverSpeedTestPresetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBDiscoverSpeedTestPresetsResponse.ProtoReflect.Descriptor instead.
func (*PBDiscoverSpeedTestPresetsResponse) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{13}
}

func (x *PBDiscoverSpeedTestPresetsResponse) GetPresets() *PBStringMap {
	if x != nil {
		return x.Presets
	}
	return nil
}

func (x *PBDiscoverSpeedTestPresetsResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type PBRunSpeedTestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	ProviderId    string                 `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Mode          PBSpeedTestMode        `protobuf:"varint,3,opt,name=mode,proto3,enum=com.bghorizon.proxytoolboxgui.proto.PBSpeedTestMode" json:"mode,omitempty"`
	Rounds        int32                  `protobuf:"varint,4,opt,name=rounds,proto3" json:"rounds,omitempty"`
	Timeout       int32                  `protobuf:"varint,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	TargetBytes   int64                  `protobuf:"varint,6,opt,name=target_bytes,json=targetBytes,proto3" json:"target_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBRunSpeedTestsRequest) Reset() {
	*x = PBRunSpeedTestsRequest{}
	mi := &file_bridge_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBRunSpeedTestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBRunSpeedTestsRequest) ProtoMessage() {}

func (x *PBRunSpeedTestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBRunSpeedTestsRequest.ProtoReflect.Descriptor instead.
func (*PBRunSpeedTestsRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{14}
}

func (x *PBRunSpeedTestsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PBRunSpeedTestsRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *PBRunSpeedTestsRequest) GetMode() PBSpeedTestMode {
	if x != nil {
		return x.Mode
	}
	return PBSpeedTestMode_DOWNLOAD
}

func (x *PBRunSpeedTestsRequest) GetRounds() int32 {
	if x != nil {
		return x.Rounds
	}
	return 0
}

func (x *PBRunSpeedTestsRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *PBRunSpeedTestsRequest) GetTargetBytes() int64 {
	if x != nil {
		return x.TargetBytes
	}
	return 0
}

type PBSpeedTestResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Speed         float64                `protobuf:"fixed64,2,opt,name=speed,proto3" json:"speed,omitempty"` // bytes/s
	Error         *string                `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBSpeedTestResult) Reset() {
	*x = PBSpeedTestResult{}
	mi := &file_bridge_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBSpeedTestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBSpeedTestResult) ProtoMessage() {}

func (x *PBSpeedTestResult) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBSpeedTestResult.ProtoReflect.Descriptor instead.
func (*PBSpeedTestResult) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{15}
}

func (x *PBSpeedTestResult) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *PBSpeedTestResult) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *PBSpeedTestResult) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type PBRunSpeedTestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*PBSpeedTestResult   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBRunSpeedTestsResponse) Reset() {
	*x = PBRunSpeedTestsResponse{}
	mi := &file_bridge_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBRunSpeedTestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBRunSpeedTestsResponse) ProtoMessage() {}

func (x *PBRunSpeedTestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBRunSpeedTestsResponse.ProtoReflect.Descriptor instead.
func (*PBRunSpeedTestsResponse) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{16}
}

func (x *PBRunSpeedTestsResponse) GetResults() []*PBSpeedTestResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *PBRunSpeedTestsResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_bridge_proto protoreflect.FileDescriptor

const file_bridge_proto_rawDesc = "" +
	"\n" +
	"\fbridge.proto\x12#com.bghorizon.proxytoolboxgui.proto\"P\n" +
	"\fPBWorkerInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"_\n" +
	"\x10PBWorkerInfoList\x12K\n" +
	"\aworkers\x18\x01 \x03(\v21.com.bghorizon.proxytoolboxgui.proto.PBWorkerInfoR\aworkers\"R\n" +
	"\rPBProxyConfig\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x19\n" +
	"\bconn_uri\x18\x02 \x01(\tR\aconnUri\x12\x14\n" +
	"\x05delay\x18\x03 \x01(\x03R\x05delay\"a\n" +
	"\x11PBProxyConfigList\x12L\n" +
	"\aconfigs\x18\x01 \x03(\v22.com.bghorizon.proxytoolboxgui.proto.PBProxyConfigR\aconfigs\"\x9a\x01\n" +
	"\vPBStringMap\x12Q\n" +
	"\x05items\x18\x01 \x03(\v2;.com.bghorizon.proxytoolboxgui.proto.PBStringMap.ItemsEntryR\x05items\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\x18PBDiscoverWorkersRequest\x12!\n" +
	"\flibrary_path\x18\x01 \x01(\tR\vlibraryPath\"\x91\x01\n" +
	"\x19PBDiscoverWorkersResponse\x12O\n" +
	"\aworkers\x18\x01 \x01(\v25.com.bghorizon.proxytoolboxgui.proto.PBWorkerInfoListR\aworkers\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"^\n" +
	"\x19PBInitializeRunnerRequest\x12\x1f\n" +
	"\vworker_path\x18\x01 \x01(\tR\n" +
	"workerPath\x12 \n" +
	"\flow_mem_mode\x18\x02 \x01(\bR\n" +
	"lowMemMode\"[\n" +
	"\x1aPBInitializeRunnerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x92\x01\n" +
	"\x16PBParseConfigsResponse\x12S\n" +
	"\fparse_errors\x18\x01 \x01(\v20.com.bghorizon.proxytoolboxgui.proto.PBStringMapR\vparseErrors\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x9b\x01\n" +
	"\x19PBValidateConfigsResponse\x12Y\n" +
	"\x0fvalidate_errors\x18\x01 \x01(\v20.com.bghorizon.proxytoolboxgui.proto.PBStringMapR\x0evalidateErrors\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xc8\x01\n" +
	"\x18PBRunLatencyTestsRequest\x12\x19\n" +
	"\btest_url\x18\x01 \x01(\tR\atestUrl\x12%\n" +
	"\x0elatency_rounds\x18\x02 \x01(\x05R\rlatencyRounds\x12#\n" +
	"\rround_timeout\x18\x03 \x01(\x05R\froundTimeout\x12&\n" +
	"\x0ftest_by_batches\x18\x04 \x01(\bR\rtestByBatches\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x05 \x01(\x05R\tbatchSize\"\x92\x01\n" +
	"\x19PBRunLatencyTestsResponse\x12P\n" +
	"\aconfigs\x18\x01 \x01(\v26.com.bghorizon.proxytoolboxgui.proto.PBProxyConfigListR\aconfigs\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x95\x01\n" +
	"\"PBDiscoverSpeedTestPresetsResponse\x12J\n" +
	"\apresets\x18\x01 \x01(\v20.com.bghorizon.proxytoolboxgui.proto.PBStringMapR\apresets\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xec\x01\n" +
	"\x16PBRunSpeedTestsRequest\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\tR\n" +
	"providerId\x12H\n" +
	"\x04mode\x18\x03 \x01(\x0e24.com.bghorizon.proxytoolboxgui.proto.PBSpeedTestModeR\x04mode\x12\x16\n" +
	"\x06rounds\x18\x04 \x01(\x05R\x06rounds\x12\x18\n" +
	"\atimeout\x18\x05 \x01(\x05R\atimeout\x12!\n" +
	"\ftarget_bytes\x18\x06 \x01(\x03R\vtargetBytes\"`\n" +
	"\x11PBSpeedTestResult\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x14\n" +
	"\x05speed\x18\x02 \x01(\x01R\x05speed\x12\x19\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x90\x01\n" +
	"\x17PBRunSpeedTestsResponse\x12P\n" +
	"\aresults\x18\x01 \x03(\v26.com.bghorizon.proxytoolboxgui.proto.PBSpeedTestResultR\aresults\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error*+\n" +
	"\x0fPBSpeedTestMode\x12\f\n" +
	"\bDOWNLOAD\x10\x00\x12\n" +
	"\n" +
	"\x06UPLOAD\x10\x01Bg\n" +
	"#com.bghorizon.proxytoolboxgui.protoP\x01Z>github.com/bluegradienthorizon/proxytoolboxgui/gowrapper/protob\x06proto3"

var (
	file_bridge_proto_rawDescOnce sync.Once
	file_bridge_proto_rawDescData []byte
)

func file_bridge_proto_rawDescGZIP() []byte {
	file_bridge_proto_rawDescOnce.Do(func() {
		file_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bridge_proto_rawDesc), len(file_bridge_proto_rawDesc)))
	})
	return file_bridge_proto_rawDescData
}

var file_bridge_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_bridge_proto_goTypes = []any{
	(PBSpeedTestMode)(0),                       // 0: com.bghorizon.proxytoolboxgui.proto.PBSpeedTestMode
	(*PBWorkerInfo)(nil),                       // 1: com.bghorizon.proxytoolboxgui.proto.PBWorkerInfo
	(*PBWorkerInfoList)(nil),                   // 2: com.bghorizon.proxytoolboxgui.proto.PBWorkerInfoList
	(*PBProxyConfig)(nil),                      // 3: com.bghorizon.proxytoolboxgui.proto.PBProxyConfig
	(*PBProxyConfigList)(nil),                  // 4: com.bghorizon.proxytoolboxgui.proto.PBProxyConfigList
	(*PBStringMap)(nil),                        // 5: com.bghorizon.proxytoolboxgui.proto.PBStringMap
	(*PBDiscoverWorkersRequest)(nil),           // 6: com.bghorizon.proxytoolboxgui.proto.PBDiscoverWorkersRequest
	(*PBDiscoverWorkersResponse)(nil),          // 7: com.bghorizon.proxytoolboxgui.proto.PBDiscoverWorkersResponse
	(*PBInitializeRunnerRequest)(nil),          // 8: com.bghorizon.proxytoolboxgui.proto.PBInitializeRunnerRequest
	(*PBInitializeRunnerResponse)(nil),         // 9: com.bghorizon.proxytoolboxgui.proto.PBInitializeRunnerResponse
	(*PBParseConfigsResponse)(nil),             // 10: com.bghorizon.proxytoolboxgui.proto.PBParseConfigsResponse
	(*PBValidateConfigsResponse)(nil),          // 11: com.bghorizon.proxytoolboxgui.proto.PBValidateConfigsResponse
	(*PBRunLatencyTestsRequest)(nil),           // 12: com.bghorizon.proxytoolboxgui.proto.PBRunLatencyTestsRequest
	(*PBRunLatencyTestsResponse)(nil),          // 13: com.bghorizon.proxytoolboxgui.proto.PBRunLatencyTestsResponse
	(*PBDiscoverSpeedTestPresetsResponse)(nil), // 14: com.bghorizon.proxytoolboxgui.proto.PBDiscoverSpeedTestPresetsResponse
	(*PBRunSpeedTestsRequest)(nil),             // 15: com.bghorizon.proxytoolboxgui.proto.PBRunSpeedTestsRequest
	(*PBSpeedTestResult)(nil),                  // 16: com.bghorizon.proxytoolboxgui.proto.PBSpeedTestResult
	(*PBRunSpeedTestsResponse)(nil),            // 17: com.bghorizon.proxytoolboxgui.proto.PBRunSpeedTestsResponse
	nil,                                        // 18: com.bghorizon.proxytoolboxgui.proto.PBStringMap.ItemsEntry
}
var file_bridge_proto_depIdxs = []int32{
	1,  // 0: com.bghorizon.proxytoolboxgui.proto.PBWorkerInfoList.workers:type_name -> com.bghorizon.proxytoolboxgui.proto.PBWorkerInfo
	3,  // 1: com.bghorizon.proxytoolboxgui.proto.PBProxyConfigList.configs:type_name -> com.bghorizon.proxytoolboxgui.proto.PBProxyConfig
	18, // 2: com.bghorizon.proxytoolboxgui.proto.PBStringMap.items:type_name -> com.bghorizon.proxytoolboxgui.proto.PBStringMap.ItemsEntry
	2,  // 3: com.bghorizon.proxytoolboxgui.proto.PBDiscoverWorkersResponse.workers:type_name -> com.bghorizon.proxytoolboxgui.proto.PBWorkerInfoList
	5,  // 4: com.bghorizon.proxytoolboxgui.proto.PBParseConfigsResponse.parse_errors:type_name -> com.bghorizon.proxytoolboxgui.proto.PBStringMap
	5,  // 5: com.bghorizon.proxytoolboxgui.proto.PBValidateConfigsResponse.validate_errors:type_name -> com.bghorizon.proxytoolboxgui.proto.PBStringMap
	4,  // 6: com.bghorizon.proxytoolboxgui.proto.PBRunLatencyTestsResponse.configs:type_name -> com.bghorizon.proxytoolboxgui.proto.PBProxyConfigList
	5,  // 7: com.bghorizon.proxytoolboxgui.proto.PBDiscoverSpeedTestPresetsResponse.presets:type_name -> com.bghorizon.proxytoolboxgui.proto.PBStringMap
	0,  // 8: com.bghorizon.proxytoolboxgui.proto.PBRunSpeedTestsRequest.mode:type_name -> com.bghorizon.proxytoolboxgui.proto.PBSpeedTestMode
	16, // 9: com.bghorizon.proxytoolboxgui.proto.PBRunSpeedTestsResponse.results:type_name -> com.bghorizon.proxytoolboxgui.proto.PBSpeedTestResult
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_bridge_proto_init() }
func file_bridge_proto_init() {
	if File_bridge_proto != nil {
		return
	}
	file_bridge_proto_msgTypes[6].OneofWrappers = []any{}
	file_bridge_proto_msgTypes[8].OneofWrappers = []any{}
	file_bridge_proto_msgTypes[9].OneofWrappers = []any{}
	file_bridge_proto_msgTypes[10].OneofWrappers = []any{}
	file_bridge_proto_msgTypes[12].OneofWrappers = []any{}
	file_bridge_proto_msgTypes[13].OneofWrappers = []any{}
	file_bridge_proto_msgTypes[15].OneofWrappers = []any{}
	file_bridge_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bridge_proto_rawDesc), len(file_bridge_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bridge_proto_goTypes,
		DependencyIndexes: file_bridge_proto_depIdxs,
		EnumInfos:         file_bridge_proto_enumTypes,
		MessageInfos:      file_bridge_proto_msgTypes,
	}.Build()
	File_bridge_proto = out.File
	file_bridge_proto_goTypes = nil
	file_bridge_proto_depIdxs = nil
}
