// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: bridge.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PBWorkerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBWorkerInfo) Reset() {
	*x = PBWorkerInfo{}
	mi := &file_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBWorkerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBWorkerInfo) ProtoMessage() {}

func (x *PBWorkerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBWorkerInfo.ProtoReflect.Descriptor instead.
func (*PBWorkerInfo) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *PBWorkerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PBWorkerInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PBWorkerInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type PBWorkerInfoList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workers       []*PBWorkerInfo        `protobuf:"bytes,1,rep,name=workers,proto3" json:"workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBWorkerInfoList) Reset() {
	*x = PBWorkerInfoList{}
	mi := &file_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBWorkerInfoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBWorkerInfoList) ProtoMessage() {}

func (x *PBWorkerInfoList) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBWorkerInfoList.ProtoReflect.Descriptor instead.
func (*PBWorkerInfoList) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *PBWorkerInfoList) GetWorkers() []*PBWorkerInfo {
	if x != nil {
		return x.Workers
	}
	return nil
}

type PBProxyConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	ConnUri       string                 `protobuf:"bytes,2,opt,name=conn_uri,json=connUri,proto3" json:"conn_uri,omitempty"`
	Delay         int64                  `protobuf:"varint,3,opt,name=delay,proto3" json:"delay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBProxyConfig) Reset() {
	*x = PBProxyConfig{}
	mi := &file_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBProxyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBProxyConfig) ProtoMessage() {}

func (x *PBProxyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBProxyConfig.ProtoReflect.Descriptor instead.
func (*PBProxyConfig) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *PBProxyConfig) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *PBProxyConfig) GetConnUri() string {
	if x != nil {
		return x.ConnUri
	}
	return ""
}

func (x *PBProxyConfig) GetDelay() int64 {
	if x != nil {
		return x.Delay
	}
	return 0
}

type PBProxyConfigList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*PBProxyConfig       `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBProxyConfigList) Reset() {
	*x = PBProxyConfigList{}
	mi := &file_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBProxyConfigList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBProxyConfigList) ProtoMessage() {}

func (x *PBProxyConfigList) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBProxyConfigList.ProtoReflect.Descriptor instead.
func (*PBProxyConfigList) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *PBProxyConfigList) GetConfigs() []*PBProxyConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

type PBStringMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         map[string]string      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBStringMap) Reset() {
	*x = PBStringMap{}
	mi := &file_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBStringMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBStringMap) ProtoMessage() {}

func (x *PBStringMap) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBStringMap.ProtoReflect.Descriptor instead.
func (*PBStringMap) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{4}
}

func (x *PBStringMap) GetItems() map[string]string {
	if x != nil {
		return x.Items
	}
	return nil
}

type PBNativeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Error string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PBNativeResponse_Workers
	//	*PBNativeResponse_Configs
	//	*PBNativeResponse_StringMap
	//	*PBNativeResponse_Success
	Payload       isPBNativeResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBNativeResponse) Reset() {
	*x = PBNativeResponse{}
	mi := &file_bridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBNativeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBNativeResponse) ProtoMessage() {}

func (x *PBNativeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBNativeResponse.ProtoReflect.Descriptor instead.
func (*PBNativeResponse) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{5}
}

func (x *PBNativeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PBNativeResponse) GetPayload() isPBNativeResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PBNativeResponse) GetWorkers() *PBWorkerInfoList {
	if x != nil {
		if x, ok := x.Payload.(*PBNativeResponse_Workers); ok {
			return x.Workers
		}
	}
	return nil
}

func (x *PBNativeResponse) GetConfigs() *PBProxyConfigList {
	if x != nil {
		if x, ok := x.Payload.(*PBNativeResponse_Configs); ok {
			return x.Configs
		}
	}
	return nil
}

func (x *PBNativeResponse) GetStringMap() *PBStringMap {
	if x != nil {
		if x, ok := x.Payload.(*PBNativeResponse_StringMap); ok {
			return x.StringMap
		}
	}
	return nil
}

func (x *PBNativeResponse) GetSuccess() bool {
	if x != nil {
		if x, ok := x.Payload.(*PBNativeResponse_Success); ok {
			return x.Success
		}
	}
	return false
}

type isPBNativeResponse_Payload interface {
	isPBNativeResponse_Payload()
}

type PBNativeResponse_Workers struct {
	Workers *PBWorkerInfoList `protobuf:"bytes,2,opt,name=workers,proto3,oneof"`
}

type PBNativeResponse_Configs struct {
	Configs *PBProxyConfigList `protobuf:"bytes,3,opt,name=configs,proto3,oneof"`
}

type PBNativeResponse_StringMap struct {
	StringMap *PBStringMap `protobuf:"bytes,4,opt,name=string_map,json=stringMap,proto3,oneof"`
}

type PBNativeResponse_Success struct {
	Success bool `protobuf:"varint,5,opt,name=success,proto3,oneof"`
}

func (*PBNativeResponse_Workers) isPBNativeResponse_Payload() {}

func (*PBNativeResponse_Configs) isPBNativeResponse_Payload() {}

func (*PBNativeResponse_StringMap) isPBNativeResponse_Payload() {}

func (*PBNativeResponse_Success) isPBNativeResponse_Payload() {}

var File_bridge_proto protoreflect.FileDescriptor

const file_bridge_proto_rawDesc = "" +
	"\n" +
	"\fbridge.proto\x12#com.bghorizon.proxytoolboxgui.proto\"P\n" +
	"\fPBWorkerInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"_\n" +
	"\x10PBWorkerInfoList\x12K\n" +
	"\aworkers\x18\x01 \x03(\v21.com.bghorizon.proxytoolboxgui.proto.PBWorkerInfoR\aworkers\"R\n" +
	"\rPBProxyConfig\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x19\n" +
	"\bconn_uri\x18\x02 \x01(\tR\aconnUri\x12\x14\n" +
	"\x05delay\x18\x03 \x01(\x03R\x05delay\"a\n" +
	"\x11PBProxyConfigList\x12L\n" +
	"\aconfigs\x18\x01 \x03(\v22.com.bghorizon.proxytoolboxgui.proto.PBProxyConfigR\aconfigs\"\x9a\x01\n" +
	"\vPBStringMap\x12Q\n" +
	"\x05items\x18\x01 \x03(\v2;.com.bghorizon.proxytoolboxgui.proto.PBStringMap.ItemsEntryR\x05items\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc9\x02\n" +
	"\x10PBNativeResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12Q\n" +
	"\aworkers\x18\x02 \x01(\v25.com.bghorizon.proxytoolboxgui.proto.PBWorkerInfoListH\x00R\aworkers\x12R\n" +
	"\aconfigs\x18\x03 \x01(\v26.com.bghorizon.proxytoolboxgui.proto.PBProxyConfigListH\x00R\aconfigs\x12Q\n" +
	"\n" +
	"string_map\x18\x04 \x01(\v20.com.bghorizon.proxytoolboxgui.proto.PBStringMapH\x00R\tstringMap\x12\x1a\n" +
	"\asuccess\x18\x05 \x01(\bH\x00R\asuccessB\t\n" +
	"\apayloadBg\n" +
	"#com.bghorizon.proxytoolboxgui.protoP\x01Z>github.com/bluegradienthorizon/proxytoolboxgui/gowrapper/protob\x06proto3"

var (
	file_bridge_proto_rawDescOnce sync.Once
	file_bridge_proto_rawDescData []byte
)

func file_bridge_proto_rawDescGZIP() []byte {
	file_bridge_proto_rawDescOnce.Do(func() {
		file_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bridge_proto_rawDesc), len(file_bridge_proto_rawDesc)))
	})
	return file_bridge_proto_rawDescData
}

var file_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_bridge_proto_goTypes = []any{
	(*PBWorkerInfo)(nil),      // 0: com.bghorizon.proxytoolboxgui.proto.PBWorkerInfo
	(*PBWorkerInfoList)(nil),  // 1: com.bghorizon.proxytoolboxgui.proto.PBWorkerInfoList
	(*PBProxyConfig)(nil),     // 2: com.bghorizon.proxytoolboxgui.proto.PBProxyConfig
	(*PBProxyConfigList)(nil), // 3: com.bghorizon.proxytoolboxgui.proto.PBProxyConfigList
	(*PBStringMap)(nil),       // 4: com.bghorizon.proxytoolboxgui.proto.PBStringMap
	(*PBNativeResponse)(nil),  // 5: com.bghorizon.proxytoolboxgui.proto.PBNativeResponse
	nil,                       // 6: com.bghorizon.proxytoolboxgui.proto.PBStringMap.ItemsEntry
}
var file_bridge_proto_depIdxs = []int32{
	0, // 0: com.bghorizon.proxytoolboxgui.proto.PBWorkerInfoList.workers:type_name -> com.bghorizon.proxytoolboxgui.proto.PBWorkerInfo
	2, // 1: com.bghorizon.proxytoolboxgui.proto.PBProxyConfigList.configs:type_name -> com.bghorizon.proxytoolboxgui.proto.PBProxyConfig
	6, // 2: com.bghorizon.proxytoolboxgui.proto.PBStringMap.items:type_name -> com.bghorizon.proxytoolboxgui.proto.PBStringMap.ItemsEntry
	1, // 3: com.bghorizon.proxytoolboxgui.proto.PBNativeResponse.workers:type_name -> com.bghorizon.proxytoolboxgui.proto.PBWorkerInfoList
	3, // 4: com.bghorizon.proxytoolboxgui.proto.PBNativeResponse.configs:type_name -> com.bghorizon.proxytoolboxgui.proto.PBProxyConfigList
	4, // 5: com.bghorizon.proxytoolboxgui.proto.PBNativeResponse.string_map:type_name -> com.bghorizon.proxytoolboxgui.proto.PBStringMap
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_bridge_proto_init() }
func file_bridge_proto_init() {
	if File_bridge_proto != nil {
		return
	}
	file_bridge_proto_msgTypes[5].OneofWrappers = []any{
		(*PBNativeResponse_Workers)(nil),
		(*PBNativeResponse_Configs)(nil),
		(*PBNativeResponse_StringMap)(nil),
		(*PBNativeResponse_Success)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bridge_proto_rawDesc), len(file_bridge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bridge_proto_goTypes,
		DependencyIndexes: file_bridge_proto_depIdxs,
		MessageInfos:      file_bridge_proto_msgTypes,
	}.Build()
	File_bridge_proto = out.File
	file_bridge_proto_goTypes = nil
	file_bridge_proto_depIdxs = nil
}
