/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/bluegradienthorizon/proxytoolboxgui/gowrapper */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "jni_bridge.go"

#include <jni.h>
#include <stdlib.h>
#include <stdbool.h>

static jstring NewString(JNIEnv *env, const jchar *chars, jsize len) {
    return (*env)->NewString(env, chars, len);
}

static jsize GetStringLength(JNIEnv *env, jstring str) {
    return (*env)->GetStringLength(env, str);
}

static const jchar* GetStringChars(JNIEnv *env, jstring str) {
    return (*env)->GetStringChars(env, str, NULL);
}

static void ReleaseStringChars(JNIEnv *env, jstring str, const jchar *chars) {
    (*env)->ReleaseStringChars(env, str, chars);
}

static jclass GetObjectClass(JNIEnv *env, jobject obj) {
    return (*env)->GetObjectClass(env, obj);
}

static jmethodID GetMethodID(JNIEnv *env, jclass clazz, const char *name, const char *sig) {
    return (*env)->GetMethodID(env, clazz, name, sig);
}

static void callOnRoundStarted(JNIEnv *env, jobject cb, jmethodID mid, jlong batch, jlong round, jlong total) {
    (*env)->CallVoidMethod(env, cb, mid, batch, round, total);
}

static void callOnProgress(JNIEnv *env, jobject cb, jmethodID mid, jstring tag, jlong delay, jboolean failed) {
    (*env)->CallVoidMethod(env, cb, mid, tag, delay, failed);
}

static void callOnRoundEnded(JNIEnv *env, jobject cb, jmethodID mid, jlong batch, jlong round) {
    (*env)->CallVoidMethod(env, cb, mid, batch, round);
}

static void callOnSpeedProgress(JNIEnv *env, jobject cb, jmethodID mid, jstring tag, jdouble speed, jboolean failed) {
    (*env)->CallVoidMethod(env, cb, mid, tag, speed, failed);
}

static void DeleteLocalRef(JNIEnv *env, jobject obj) {
    (*env)->DeleteLocalRef(env, obj);
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern jstring Java_com_bghorizon_proxytoolboxgui_data_GoBridgeNative_nativeDiscoverWorkers(JNIEnv* env, jclass clazz, jstring libraryPath);
extern void Java_com_bghorizon_proxytoolboxgui_data_GoBridgeNative_nativeStopTests(JNIEnv* env, jclass clazz);
extern jstring Java_com_bghorizon_proxytoolboxgui_data_GoBridgeNative_nativeInitializeRunner(JNIEnv* env, jclass clazz, jstring workerPath);
extern jstring Java_com_bghorizon_proxytoolboxgui_data_GoBridgeNative_nativeParseConfigs(JNIEnv* env, jclass clazz, jstring connUrisJson);
extern jstring Java_com_bghorizon_proxytoolboxgui_data_GoBridgeNative_nativeValidateConfigs(JNIEnv* env, jclass clazz);
extern jstring Java_com_bghorizon_proxytoolboxgui_data_GoBridgeNative_nativeRunLatencyTests(JNIEnv* env, jclass clazz, jstring testUrl, jint latencyRounds, jint roundTimeout, jboolean testByBatches, jint batchSize, jobject callback);
extern jstring Java_com_bghorizon_proxytoolboxgui_data_GoBridgeNative_nativeRunSpeedTests(JNIEnv* env, jclass clazz, jstring provider, jstring modeStr, jlong targetBytes, jint speedRounds, jint roundTimeout, jboolean testByBatches, jint batchSize, jstring tagsJson, jobject callback);

#ifdef __cplusplus
}
#endif
