name: CI Build

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-platforms.yml
    with:
      build_profile: debug
