syntax = "proto3";

package com.bghorizon.proxytoolboxgui.proto;

option java_package = "com.bghorizon.proxytoolboxgui.proto";
option java_multiple_files = true;
option go_package = "github.com/bluegradienthorizon/proxytoolboxgui/gowrapper/proto";

message PBWorkerInfo {
    string name = 1;
    string version = 2;
    string path = 3;
}

message PBWorkerInfoList {
    repeated PBWorkerInfo workers = 1;
}

message PBProxyConfig {
    string tag = 1;
    string conn_uri = 2;
    int64 delay = 3;
}

message PBProxyConfigList {
    repeated PBProxyConfig configs = 1;
}

message PBStringMap {
    map<string, string> items = 1;
}

message PBDiscoverWorkersRequest {
    string library_path = 1;
}

message PBDiscoverWorkersResponse {
    PBWorkerInfoList workers = 1;
    optional string error = 2;
}

message PBInitializeRunnerRequest {
    string worker_path = 1;
}

message PBInitializeRunnerResponse {
    bool success = 1;
    optional string error = 2;
}

message PBParseConfigsResponse {
    PBStringMap parse_errors = 1;
    optional string error = 2;
}

message PBValidateConfigsResponse {
    PBStringMap validate_errors = 1;
    optional string error = 2;
}

message PBRunLatencyTestsRequest {
    string test_url = 1;
    int32 latency_rounds = 2;
    int32 round_timeout = 3;
    bool test_by_batches = 4;
    int32 batch_size = 5;
}

message PBRunLatencyTestsResponse {
    PBProxyConfigList configs = 1;
    optional string error = 2;
}
